spring.datasource.url=jdbc:mysql://localhost:3306/quan_ly_luong?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SMTP config for "Gui mail" phieu luong
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenduykhang.k15@stu.upt.edu.vn
spring.mail.password=myosfephotbibdwb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
